---

- name: install hotfix (PS >= 4) - {{ hotfix_download.kb }}
  community.windows.win_hotfix:
    hotfix_kb: '{{ hotfix_download.kb }}'
    source: '{{ hotfix_temp_directory }}\{{ hotfix_download.file }}'
    state: present
  register: hotfix_install
